services:
  postgres:
    image: postgres:15-alpine
    container_name: near_cities_db
    # restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - ./.env.db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U dev_root -d dev"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
  
  redis:
    image: redis:alpine
    container_name: near_cities_redis
    # restart: always
    ports:
      - "127.0.0.1:6380:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
  
  adminer:
    image: adminer
    container_name: near_cities_adminer
    # restart: always
    ports:
      - "127.0.0.1:8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128MB
  
  app:
    build: ./app
    container_name: near_cities_app
    command: python main.py
    # restart: always
    volumes:
      - ./app:/app
    env_file:
      - ./.env.db
      - ./app/.env
    ports:
      - "127.0.0.1:8001:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
